#!/usr/bin/env python3
import sys
import socket

def server(port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('', port))
    s.listen(1)
    conn, _ = s.accept()
    try:
        while True:
            header = conn.recv(2)
            if not header or len(header) < 2:
                break
            data_length = int.from_bytes(header, 'big')
            data = conn.recv(data_length)
            sys.stdout.buffer.write(data)
            sys.stdout.buffer.flush()
    finally:
        conn.close()
        s.close()

def client(host, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((host, port))
    try:
        while True:
            chunk = sys.stdin.buffer.read(1024)
            if not chunk: 
                break
            header = len(chunk).to_bytes(2, 'big')  
            s.sendall(header)
            s.sendall(chunk)
    finally:
        s.close()

def main():
    argv = sys.argv
    if argv[1] == "-l":
        port = int(argv[2])
        server(port)

    else:
        host = argv[1]
        port = int(argv[2])
        client(host, port)

if __name__ == "__main__":
    main()
